/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs3308.mission06;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
